/* In the form of register */
export const SEND_DATA_FORM = 'SEND_DATA_FORM'
export const SEND_DATA_FORM_SUCCESS = 'SEND_DATA_FORM_SUCCESS'
export const SEND_DATA_FORM_ERROR = 'SEND_DATA_FORM_ERROR'
export const UPDATE_DATA_FORMS = 'UPDATE_DATA_FORMS'
export const FILTER_PROVINCE = 'FILTER_PROVINCE'
export const VALIDATE_DATA_FORM = 'VALIDATE_DATA_FORM'

/* In the Technologies context */
export const GET_TECHNOLOGIES = 'GET_TECHNOLOGIES'
export const GET_TECHNOLOGIES_SUCCESS = 'GET_TECHNOLOGIES_SUCCESS'
export const GET_TECHNOLOGIES_ERROR = 'GET_TECHNOLOGIES_ERROR'
export const ADD_REMOVE_FAVORITE_LIST = 'ADD_REMOVE_FAVORITE_LIST'
