/* In the form of register */
export const SEND_DATA_FORM = 'SEND_DATA_FORM'
export const SEND_DATA_FORM_SUCCESS = 'SEND_DATA_FORM_SUCCESS'
export const SEND_DATA_FORM_ERROR = 'SEND_DATA_FORM_ERROR'
export const UPDATE_DATA_FORMS = 'UPDATE_DATA_FORMS'
export const FILTER_PROVINCE = 'FILTER_PROVINCE'
export const VALIDATE_DATA_FORM = 'VALIDATE_DATA_FORM'
